### ISSUE TITLE
urllib2.HTTPError: HTTP Error 403: Forbidden

### ISSUE THREAD

**Issue by Tangoes** [jpgleyva/sickbeard-elitetorrent-rss#1]
Me sale este error al ejecutar. ¿Tal vez han cambiado algo en la web?

```
test@box$ ./eliteTorrent.py 
Traceback (most recent call last):
  File "./eliteTorrent.py", line 20, in <module>
    rss = urllib2.urlopen('http://elitetorrent.net/rss.php')
  File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 403: Forbidden
```

**Comment by Tangoes** [comment]
Veo que tampoco se puede añadir a sickbeard,entiendo que este script es muy viejuno. Olvidé mirar la fecha.
